name: get_meta
description: Fetches sample metadata from Gemma database API
keywords:
  - gemma
  - metadata
  - api

input:
  - meta:
      type: map
      description: Groovy Map containing study metadata
  - study_path:
      type: directory
      description: Path to study data
  - gemma_username:
      type: string
      description: Gemma API username
  - gemma_password:
      type: string
      description: Gemma API password

output:
  - meta:
      type: file
      description: Sample metadata TSV
      pattern: "**/sample_meta.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@rachadele"
maintainers:
  - "@rachadele"
